CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,role TEXT NOT NULL,name TEXT NOT NULL,matric TEXT UNIQUE,email TEXT,phone TEXT NOT NULL UNIQUE,place TEXT,biz TEXT,cat TEXT,salt TEXT NOT NULL,pw TEXT NOT NULL,created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(h TEXT PRIMARY KEY,uid INTEGER NOT NULL,exp INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS vendor_codes(code TEXT PRIMARY KEY,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS attempts(k TEXT NOT NULL,t INTEGER NOT NULL);
INSERT OR IGNORE INTO vendor_codes(code) VALUES('ACUSHOP');
