// Starter list of Nigerian tertiary institutions: [name, short name, state, kind].
// Loaded into the `schools` table the first time the app runs, and again (new names only) whenever SCHOOLS_V goes up. Admins can add, rename or approve
// schools later from Admin > Schools, so this list does not need to be complete or perfect.
export const STATES=['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','FCT','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara'];
// Bump this when schools are added, so existing databases pick up the new ones.
export const SCHOOLS_V=2;
export const SCHOOLS=[
// Federal universities
['University of Lagos','UNILAG','Lagos','university'],['University of Ibadan','UI','Oyo','university'],['Obafemi Awolowo University','OAU','Osun','university'],
['University of Nigeria, Nsukka','UNN','Enugu','university'],['Ahmadu Bello University','ABU','Kaduna','university'],['University of Benin','UNIBEN','Edo','university'],
['University of Ilorin','UNILORIN','Kwara','university'],['University of Port Harcourt','UNIPORT','Rivers','university'],['University of Jos','UNIJOS','Plateau','university'],
['University of Calabar','UNICAL','Cross River','university'],['University of Uyo','UNIUYO','Akwa Ibom','university'],['University of Abuja','UNIABUJA','FCT','university'],
['Bayero University Kano','BUK','Kano','university'],['University of Maiduguri','UNIMAID','Borno','university'],['Usmanu Danfodiyo University','UDUS','Sokoto','university'],
['Nnamdi Azikiwe University','UNIZIK','Anambra','university'],['Federal University of Technology, Akure','FUTA','Ondo','university'],['Federal University of Technology, Owerri','FUTO','Imo','university'],
['Federal University of Technology, Minna','FUTMINNA','Niger','university'],['Modibbo Adama University, Yola','MAU','Adamawa','university'],['Federal University of Agriculture, Abeokuta','FUNAAB','Ogun','university'],
['Joseph Sarwuan Tarka University, Makurdi','JOSTUM','Benue','university'],['Michael Okpara University of Agriculture, Umudike','MOUAU','Abia','university'],['Federal University of Petroleum Resources, Effurun','FUPRE','Delta','university'],
['Nigerian Defence Academy','NDA','Kaduna','university'],['Air Force Institute of Technology','AFIT','Kaduna','university'],['National Open University of Nigeria','NOUN','FCT','university'],
['Federal University Oye-Ekiti','FUOYE','Ekiti','university'],['Federal University Lokoja','FULOKOJA','Kogi','university'],['Federal University of Lafia','FULAFIA','Nasarawa','university'],
['Federal University Dutse','FUD','Jigawa','university'],['Federal University Dutsin-Ma','FUDMA','Katsina','university'],['Federal University of Kashere','FUKASHERE','Gombe','university'],
['Federal University Wukari','FUWUKARI','Taraba','university'],['Federal University Birnin Kebbi','FUBK','Kebbi','university'],['Federal University Gusau','FUGUS','Zamfara','university'],
['Federal University Gashua','FUGASHUA','Yobe','university'],['Alex Ekwueme Federal University, Ndufu-Alike','AE-FUNAI','Ebonyi','university'],['Federal University Otuoke','FUOTUOKE','Bayelsa','university'],
['Federal University of Health Sciences, Otukpo','FUHSO','Benue','university'],['Nigeria Police Academy, Wudil','POLAC','Kano','university'],['Nigerian Maritime University, Okerenkoko','NMU','Delta','university'],
// State universities
['Lagos State University','LASU','Lagos','university'],['Lagos State University of Science and Technology','LASUSTECH','Lagos','university'],['Lagos State University of Education','LASUED','Lagos','university'],
['Olabisi Onabanjo University','OOU','Ogun','university'],['Tai Solarin University of Education','TASUED','Ogun','university'],['Ladoke Akintola University of Technology','LAUTECH','Oyo','university'],
['Osun State University','UNIOSUN','Osun','university'],['Ekiti State University','EKSU','Ekiti','university'],['Adekunle Ajasin University','AAUA','Ondo','university'],
['Kwara State University','KWASU','Kwara','university'],['Ambrose Alli University','AAU','Edo','university'],['Edo State University Uzairue','EDSU','Edo','university'],
['Delta State University','DELSU','Delta','university'],['Rivers State University','RSU','Rivers','university'],['Ignatius Ajuru University of Education','IAUE','Rivers','university'],
['Niger Delta University','NDU','Bayelsa','university'],['Akwa Ibom State University','AKSU','Akwa Ibom','university'],['University of Cross River State','UNICROSS','Cross River','university'],
['Enugu State University of Science and Technology','ESUT','Enugu','university'],['Chukwuemeka Odumegwu Ojukwu University','COOU','Anambra','university'],['Imo State University','IMSU','Imo','university'],
['Abia State University','ABSU','Abia','university'],['Ebonyi State University','EBSU','Ebonyi','university'],['Benue State University','BSU','Benue','university'],
['Prince Abubakar Audu University','PAAU','Kogi','university'],['Nasarawa State University, Keffi','NSUK','Nasarawa','university'],['Plateau State University','PLASU','Plateau','university'],
['Kaduna State University','KASU','Kaduna','university'],['Aliko Dangote University of Science and Technology, Wudil','ADUSTECH','Kano','university'],['Yusuf Maitama Sule University','YUMSUK','Kano','university'],
["Umaru Musa Yar'adua University",'UMYU','Katsina','university'],['Sokoto State University','SSU','Sokoto','university'],['Kebbi State University of Science and Technology, Aliero','KSUSTA','Kebbi','university'],
['Gombe State University','GSU','Gombe','university'],['Adamawa State University, Mubi','ADSU','Adamawa','university'],['Taraba State University','TSU','Taraba','university'],
['Borno State University','BOSU','Borno','university'],['Yobe State University','YSU','Yobe','university'],['Bauchi State University, Gadau','BASUG','Bauchi','university'],
['Sule Lamido University, Kafin Hausa','SLU','Jigawa','university'],['Ibrahim Badamasi Babangida University, Lapai','IBBUL','Niger','university'],['Abubakar Tafawa Balewa University','ATBU','Bauchi','university'],
// Private universities
['Covenant University','CU','Ogun','university'],['Babcock University','BABCOCK','Ogun','university'],['Landmark University','LMU','Kwara','university'],
['Afe Babalola University','ABUAD','Ekiti','university'],["Redeemer's University",'RUN','Osun','university'],['Bowen University','BOWEN','Osun','university'],
['Ajayi Crowther University','ACU','Oyo','university'],['Pan-Atlantic University','PAU','Lagos','university'],['American University of Nigeria','AUN','Adamawa','university'],
['Nile University of Nigeria','NILE','FCT','university'],['Baze University','BAZE','FCT','university'],['Veritas University','VUNA','FCT','university'],
['Lead City University','LCU','Oyo','university'],['Igbinedion University, Okada','IUO','Edo','university'],['Benson Idahosa University','BIU','Edo','university'],
['Madonna University','MADONNA','Anambra','university'],['Caleb University','CALEB','Lagos','university'],['Crawford University','CRAWFORD','Ogun','university'],
['Crescent University','CUAB','Ogun','university'],['McPherson University','MCU','Ogun','university'],['Mountain Top University','MTU','Ogun','university'],
['Bells University of Technology','BELLS','Ogun','university'],['Elizade University','ELIZADE','Ondo','university'],['Achievers University','ACHIEVERS','Ondo','university'],
['Joseph Ayo Babalola University','JABU','Osun','university'],['Adeleke University','ADELEKE','Osun','university'],['Fountain University','FUO','Osun','university'],
['Anchor University','AUL','Lagos','university'],['Augustine University','AUGUSTINE','Lagos','university'],['Al-Hikmah University','AL-HIKMAH','Kwara','university'],
['Thomas Adewumi University','TAU','Kwara','university'],['Godfrey Okoye University','GOUNI','Enugu','university'],['Coal City University','CCU','Enugu','university'],
['Gregory University','GUU','Abia','university'],['Evangel University, Akaeze','EUA','Ebonyi','university'],['Novena University','NOVENA','Delta','university'],
['Admiralty University of Nigeria','ADUN','Delta','university'],['Wellspring University','WELLSPRING','Edo','university'],['Salem University','SALEM','Kogi','university'],
['Bingham University','BINGHAM','Nasarawa','university'],['Precious Cornerstone University','PCU','Oyo','university'],['Dominican University','DUI','Oyo','university'],
['Skyline University Nigeria','SUN','Kano','university'],['Al-Qalam University','AUK','Katsina','university'],['Paul University','PAUL','Anambra','university'],
// Polytechnics
['Yaba College of Technology','YABATECH','Lagos','polytechnic'],['Federal Polytechnic, Ilaro','FPI','Ogun','polytechnic'],['Moshood Abiola Polytechnic','MAPOLY','Ogun','polytechnic'],
['The Polytechnic, Ibadan','POLYIBADAN','Oyo','polytechnic'],['Federal Polytechnic, Ede','FEDEDE','Osun','polytechnic'],['Osun State Polytechnic, Iree','OSPOLY','Osun','polytechnic'],
['Federal Polytechnic, Ado-Ekiti','FPA','Ekiti','polytechnic'],['Rufus Giwa Polytechnic, Owo','RUGIPO','Ondo','polytechnic'],['Federal Polytechnic, Ile-Oluji','FEDPOLEL','Ondo','polytechnic'],
['Federal Polytechnic, Offa','FPO','Kwara','polytechnic'],['Kwara State Polytechnic','KWARAPOLY','Kwara','polytechnic'],['Auchi Polytechnic','AUCHIPOLY','Edo','polytechnic'],
['Delta State Polytechnic, Ogwashi-Uku','DSPG','Delta','polytechnic'],['Federal Polytechnic, Nekede','FPNO','Imo','polytechnic'],['Federal Polytechnic, Oko','OKOPOLY','Anambra','polytechnic'],
['Institute of Management and Technology, Enugu','IMT','Enugu','polytechnic'],['Akanu Ibiam Federal Polytechnic, Unwana','AIFPU','Ebonyi','polytechnic'],['Abia State Polytechnic','ABIAPOLY','Abia','polytechnic'],
['Federal Polytechnic, Nasarawa','FPN','Nasarawa','polytechnic'],['Federal Polytechnic, Bida','BIDAPOLY','Niger','polytechnic'],['Kaduna Polytechnic','KADPOLY','Kaduna','polytechnic'],
['Federal Polytechnic, Mubi','FPM','Adamawa','polytechnic'],['Federal Polytechnic, Bauchi','FPTB','Bauchi','polytechnic'],['Kano State Polytechnic','KANOPOLY','Kano','polytechnic'],
['Hussaini Adamu Federal Polytechnic, Kazaure','HAFEDPOLY','Jigawa','polytechnic'],['Hassan Usman Katsina Polytechnic','HUKPOLY','Katsina','polytechnic'],['Waziri Umaru Federal Polytechnic, Birnin Kebbi','WUFPBK','Kebbi','polytechnic'],
['Federal Polytechnic, Idah','FPI-IDAH','Kogi','polytechnic'],['Kogi State Polytechnic','KSP','Kogi','polytechnic'],['Captain Elechi Amadi Polytechnic','CEAPOLY','Rivers','polytechnic'],
['Ken Saro-Wiwa Polytechnic, Bori','KENPOLY','Rivers','polytechnic'],['Akwa Ibom State Polytechnic','AKWAPOLY','Akwa Ibom','polytechnic'],['Federal Polytechnic, Ekowe','FEDPOLEKOWE','Bayelsa','polytechnic'],
['Federal Polytechnic, Damaturu','FEDPODAM','Yobe','polytechnic'],['Ramat Polytechnic, Maiduguri','RAMATPOLY','Borno','polytechnic'],['Federal Polytechnic, Bali','FEDPOBALI','Taraba','polytechnic'],
['Plateau State Polytechnic','PLAPOLY','Plateau','polytechnic'],['Benue State Polytechnic, Ugbokolo','BENPOLY','Benue','polytechnic'],['Federal Polytechnic, Kaura Namoda','FEDPONAM','Zamfara','polytechnic'],
['Gateway ICT Polytechnic, Saapade','GAPOSA','Ogun','polytechnic'],['Federal Polytechnic, Kebbi (Birnin Kebbi)','FPK','Kebbi','polytechnic'],['Federal Polytechnic, Gombe','FPGOMBE','Gombe','polytechnic'],
['Federal Polytechnic, Kabo','FPKABO','Kano','polytechnic'],['Federal Polytechnic, Kaltungo','FPKALTUNGO','Gombe','polytechnic'],['Federal Polytechnic, Ukana','FPUKANA','Akwa Ibom','polytechnic'],
// Colleges and universities of education
['Federal College of Education (Technical), Akoka','FCETAKOKA','Lagos','college'],['Adeyemi Federal University of Education, Ondo','AFUED','Ondo','college'],['Alvan Ikoku Federal University of Education, Owerri','AIFUE','Imo','college'],
['Federal University of Education, Zaria','FUEZ','Kaduna','college'],['Federal College of Education, Abeokuta','FCEABK','Ogun','college'],['Emmanuel Alayande University of Education, Oyo','EAUED','Oyo','college'],
['Federal College of Education, Kano','FCEKANO','Kano','college'],['Federal College of Education, Pankshin','FCEPANKSHIN','Plateau','college'],['Federal College of Education, Okene','FCEOKENE','Kogi','college'],
['Federal College of Education, Obudu','FCEOBUDU','Cross River','college'],['Federal College of Education (Technical), Asaba','FCETASABA','Delta','college'],['Federal College of Education (Technical), Omoku','FCETOMOKU','Rivers','college'],
['Federal College of Education, Eha-Amufu','FCEEHA','Enugu','college'],['Nwafor Orizu College of Education, Nsugbe','NOCEN','Anambra','college'],['Bamidele Olumilua University of Education, Ikere','BOUESTI','Ekiti','college'],
['Federal College of Education, Yola','FCEYOLA','Adamawa','college'],['Federal College of Education (Technical), Gombe','FCETGOMBE','Gombe','college'],['Federal College of Education, Katsina','FCEKATSINA','Katsina','college'],
['Federal College of Education, Kontagora','FCEKONT','Niger','college'],['Kwara State College of Education, Ilorin','KWCOED','Kwara','college'],['Federal College of Education, Iwo','FCEIWO','Osun','college'],
// Added October 2026: more federal, state and private universities, polytechnics and colleges of education.
['Federal University of Technology, Babura','FUTB','Jigawa','university'],['Federal University of Agriculture, Zuru','FUAZ','Kebbi','university'],['Federal University of Health Sciences, Azare','FUHSA','Bauchi','university'],
['Federal University of Health Sciences, Ila-Orangun','FUHSI','Osun','university'],['Federal University of Technology, Ikot Abasi','FUTIA','Akwa Ibom','university'],['Federal University of Agriculture and Development Studies, Iragbiji','FUADS','Osun','university'],
['Federal University of Transportation, Daura','FUTD','Katsina','university'],['Federal University of Agriculture, Mubi','FUAM','Adamawa','university'],['Federal University of Environment and Technology, Ogoni','FUET','Rivers','university'],
['David Umahi Federal University of Health Sciences, Uburu','DUFUHS','Ebonyi','university'],['University of Agriculture and Environmental Sciences, Umuagwo','UAES','Imo','university'],['Nigerian Army University, Biu','NAUB','Borno','university'],
['Abiola Ajimobi Technical University, Ibadan','TECH-U','Oyo','university'],['Olusegun Agagu University of Science and Technology, Okitipupa','OAUSTECH','Ondo','university'],['University of Medical Sciences, Ondo','UNIMED','Ondo','university'],
['University of Ilesa','UNILESA','Osun','university'],['Dennis Osadebay University, Asaba','DOU','Delta','university'],['Delta State University of Science and Technology, Ozoro','DSUST','Delta','university'],
['University of Delta, Agbor','UNIDEL','Delta','university'],['Enugu State University of Medical and Applied Sciences, Igbo-Eno','ESUMAS','Enugu','university'],['Kingsley Ozumba Mbadiwe University, Ideato','KOMU','Imo','university'],
['Bayelsa Medical University, Yenagoa','BMU','Bayelsa','university'],['University of Africa, Toru-Orua','UAT','Bayelsa','university'],['Confluence University of Science and Technology, Osara','CUSTECH','Kogi','university'],
['Kogi State University, Kabba','KSUK','Kogi','university'],['Abdulkadir Kure University, Minna','AKU','Niger','university'],['Shehu Shagari University of Education, Sokoto','SSUES','Sokoto','university'],
['Zamfara State University, Talata Mafara','ZAMSUT','Zamfara','university'],['Gombe State University of Science and Technology, Kumo','GSUST','Gombe','university'],['Sa\'adatu Rimi University of Education, Kumbotso','SRUE','Kano','university'],
['Khalifa Isyaku Rabiu University, Kano','KHAIRUN','Kano','university'],['James Hope University, Lekki','JHU','Lagos','university'],['Eko University of Medicine and Health Sciences, Ijanikin','EKOUNIMED','Lagos','university'],
['Trinity University, Yaba','TRINITY','Lagos','university'],['Chrisland University, Abeokuta','CHRISLAND','Ogun','university'],['Christopher University, Mowe','CHRISTOPHER','Ogun','university'],
['Hallmark University, Ijebu-Itele','HALLMARK','Ogun','university'],['Southwestern University, Okun-Owa','SWU','Ogun','university'],['Kola Daisi University, Ibadan','KDU','Oyo','university'],
['Dominion University, Ibadan','DOMINION','Oyo','university'],['Atiba University, Oyo','ATIBA','Oyo','university'],['Oduduwa University, Ipetumodu','OUI','Osun','university'],
['Westland University, Iwo','WESTLAND','Osun','university'],['Kings University, Ode-Omu','KINGS','Osun','university'],['Hillside University of Science and Technology, Okemesi','HUST','Ekiti','university'],
['Wesley University, Ondo','WUO','Ondo','university'],['Summit University, Offa','SUMMIT','Kwara','university'],['Crown-Hill University, Eiyenkorin','CROWNHILL','Kwara','university'],
['Samuel Adegboyega University, Ogwa','SAU','Edo','university'],['Western Delta University, Oghara','WDU','Delta','university'],['Michael and Cecilia Ibru University, Agbarha-Otor','MCIU','Delta','university'],
['Edwin Clark University, Kiagbodo','ECU','Delta','university'],['Tansian University, Umunya','TANSIAN','Anambra','university'],['Caritas University, Amorji-Nike','CARITAS','Enugu','university'],
['Renaissance University, Ugbawka','RNU','Enugu','university'],['Hezekiah University, Umudi','HUU','Imo','university'],['Claretian University of Nigeria, Nekede','CUN','Imo','university'],
['Rhema University, Aba','RHEMA','Abia','university'],['Clifford University, Owerrinta','CLIFFORD','Abia','university'],['Spiritan University, Nneochi','SUN-ABIA','Abia','university'],
['Ritman University, Ikot Ekpene','RITMAN','Akwa Ibom','university'],['Obong University, Obong Ntak','OBONG','Akwa Ibom','university'],['Topfaith University, Mkpatak','TOPFAITH','Akwa Ibom','university'],
['Arthur Jarvis University, Akpabuyo','AJU','Cross River','university'],['PAMO University of Medical Sciences, Port Harcourt','PUMS','Rivers','university'],['University of Mkar, Mkar','UNIMKAR','Benue','university'],
['Karl-Kumm University, Vom','KKU','Plateau','university'],['African University of Science and Technology, Abuja','AUST','FCT','university'],['Philomath University, Kuje','PHILOMATH','FCT','university'],
['Cosmopolitan University, Abuja','COSMO','FCT','university'],['Miva Open University, Abuja','MIVA','FCT','university'],['Greenfield University, Kaduna','GREENFIELD','Kaduna','university'],
['NOK University, Kachia','NOK','Kaduna','university'],['Maryam Abacha American University of Nigeria, Kano','MAAUN','Kano','university'],['Ave Maria University, Piyanko','AMU','Nasarawa','university'],
['Khadija University, Majia','KUM','Jigawa','university'],['Kwararafa University, Wukari','KWARARAFA','Taraba','university'],['Mewar International University, Masaka','MIU','Nasarawa','university'],
['Lead British International University, Abuja','LBIU','FCT','university'],['Ahman Pategi University, Patigi','APU','Kwara','university'],['Federal Polytechnic, Daura','FPDAURA','Katsina','polytechnic'],
['Federal Polytechnic of Oil and Gas, Bonny','FPOG','Rivers','polytechnic'],['Federal Polytechnic, Ohodo','FPOHODO','Enugu','polytechnic'],['Federal Polytechnic, Ayede','FPAYEDE','Oyo','polytechnic'],
['Federal Polytechnic, N\'yak, Shendam','FPNYAK','Plateau','polytechnic'],['Federal Polytechnic, Wannune','FPWANNUNE','Benue','polytechnic'],['Federal Polytechnic, Monguno','FPMONGUNO','Borno','polytechnic'],
['Oke-Ogun Polytechnic, Saki','TOPS','Oyo','polytechnic'],['Ibarapa Polytechnic, Eruwa','IBARAPAPOLY','Oyo','polytechnic'],['Osun State College of Technology, Esa-Oke','OSCOTECH','Osun','polytechnic'],
['Edo State Polytechnic, Usen','EDOPOLY','Edo','polytechnic'],['Delta State Polytechnic, Otefe-Oghara','OGHARAPOLY','Delta','polytechnic'],['Imo State Polytechnic, Omuma','IMOPOLY','Imo','polytechnic'],
['Bayelsa State Polytechnic, Aleibiri','BYSPOLY','Bayelsa','polytechnic'],['Isa Mustapha Agwai I Polytechnic, Lafia','IMAPOLY','Nasarawa','polytechnic'],['Niger State Polytechnic, Zungeru','NIGERPOLY','Niger','polytechnic'],
['Nuhu Bamalli Polytechnic, Zaria','NUBAPOLY','Kaduna','polytechnic'],['Binyaminu Usman Polytechnic, Hadejia','BUPOLY','Jigawa','polytechnic'],['Abubakar Tatari Ali Polytechnic, Bauchi','ATAPOLY','Bauchi','polytechnic'],
['Adamawa State Polytechnic, Yola','ADAPOLY','Adamawa','polytechnic'],['Taraba State Polytechnic, Suntai','TSPOLY','Taraba','polytechnic'],['Mai Idris Alooma Polytechnic, Geidam','MAIPOLY','Yobe','polytechnic'],
['Umaru Ali Shinkafi Polytechnic, Sokoto','UASPOLY','Sokoto','polytechnic'],['Abdu Gusau Polytechnic, Talata Mafara','AGPOLY','Zamfara','polytechnic'],['Lagos City Polytechnic, Ikeja','LCP','Lagos','polytechnic'],
['Grace Polytechnic, Surulere','GRACEPOLY','Lagos','polytechnic'],['Ogun State Institute of Technology, Igbesa','OGITECH','Ogun','polytechnic'],['Allover Central Polytechnic, Sango-Ota','ACEPOLY','Ogun','polytechnic'],
['Cross River State Institute of Technology and Management, Ugep','CRSITM','Cross River','polytechnic'],['Federal College of Education (Special), Oyo','FCESOYO','Oyo','college'],['Federal College of Education (Technical), Bichi','FCETBICHI','Kano','college'],
['Federal College of Education (Technical), Potiskum','FCETPOTISKUM','Yobe','college'],['Federal College of Education (Technical), Gusau','FCETGUSAU','Zamfara','college'],['Federal College of Education (Technical), Umunze','FCETUMUNZE','Anambra','college'],
['Federal College of Education, Odugbo','FCEODUGBO','Benue','college'],['Federal College of Education, Gidan Madi','FCEGIDANMADI','Sokoto','college'],['Federal College of Education (Technical), Isu','FCETISU','Ebonyi','college'],
['Federal College of Education, Jama\'are','FCEJAMAARE','Bauchi','college'],['Federal College of Education (Technical), Ekiadolor','FCETEKIADOLOR','Edo','college'],['Oyo State College of Agriculture and Technology, Igboora','OYSCATECH','Oyo','college'],
['Osun State College of Education, Ila-Orangun','OSCOED','Osun','college'],['Tai Solarin College of Education, Omu-Ijebu','TASCE','Ogun','college'],['Kwara State College of Education, Oro','KWCOEDORO','Kwara','college'],
['Kwara State College of Education (Technical), Lafiagi','KWCOETLAF','Kwara','college'],['Kogi State College of Education, Ankpa','KSCOEANKPA','Kogi','college'],['Enugu State College of Education (Technical), Enugu','ESCET','Enugu','college'],
['Abia State College of Education (Technical), Arochukwu','ABSCOE','Abia','college'],['Ebonyi State College of Education, Ikwo','EBSCOE','Ebonyi','college'],['Akwa Ibom State College of Education, Afaha Nsit','AKSCOE','Akwa Ibom','college'],
['Isaac Jasper Boro College of Education, Sagbama','IJBCOE','Bayelsa','college'],['College of Education, Katsina-Ala','COEKA','Benue','college'],['College of Education, Oju','COEOJU','Benue','college'],
['College of Education, Akwanga','COEAKWANGA','Nasarawa','college'],['Niger State College of Education, Minna','COEMINNA','Niger','college'],['Kaduna State College of Education, Gidan Waya','KSCOEGW','Kaduna','college'],
['Isa Kaita College of Education, Dutsin-Ma','IKCOE','Katsina','college'],['Jigawa State College of Education, Gumel','JSCOE','Jigawa','college'],['Aminu Saleh College of Education, Azare','ASCOE','Bauchi','college'],
['Adamawa State College of Education, Hong','ADSCOE','Adamawa','college'],['College of Education, Jalingo','COEJALINGO','Taraba','college'],['Umar Ibn Ibrahim El-Kanemi College of Education, Bama','UIIECOE','Borno','college'],
['Adamu Augie College of Education, Argungu','AACOE','Kebbi','college'],['Zamfara State College of Education, Maru','ZACOEM','Zamfara','college'],['FCT College of Education, Zuba','FCTCOE','FCT','college'],
['College of Education, Warri','COEWARRI','Delta','college'],['Yobe State College of Education, Gashua','YOSCOE','Yobe','college'],['Gombe State College of Education, Billiri','GSCOE','Gombe','college'],
['Cross River State College of Education, Akamkpa','CRSCOE','Cross River','college']];
